[BD-18] switch from nose to pytest
edly-io/edx-analytics-pipeline pull request #2
Opened 2020-08-13 13:33 UTC by emzubair

## [BD-18] switch from nose to pytest
Updated Makefile commands as per pytest options.

**Packages Added**

- pytest-cov

**Packages Removed**

- nose
- nose-ignore-docstring

2020-08-13 14:35 UTC, ziafazal requested changes
@emzubair could you please try my suggestion?

2020-08-13 14:35 UTC, ziafazal commented on Makefile
> -coverage-local: test-local
why we removed `test-local` here?

2020-08-13 14:35 UTC, ziafazal commented on Makefile
>  	python -m coverage html
I think we can use single command to accomplish what all these `coverage` commands are doing except the `diff-cover`. Could you please try?
`coverage run -m pytest html xml -o coverage.xml`

2020-08-13 14:39 UTC, emzubair commented on Makefile
> -coverage-local: test-local
it was just of local testing purposes, reverting the change.

2020-08-17 12:16 UTC, ziafazal approved these changes
👍

2020-08-17 14:17 UTC, closed without merging